name: Fetch 10-Year Treasury Yield Daily

on:
  schedule:
    - cron: '30 22 * * *'  # JST 07:30 (UTC 22:30 of the previous day)
  workflow_dispatch:     # 手動実行も可能

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install yfinance pandas

    - name: Run fetcher script
      run: python yield_fetcher.py

    - name: Commit and push CSV
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add yield_history.csv
        git commit -m "Update yield history" || echo "No changes"
        git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
        git push origin main